# This is a basic workflow to help you get started with Actions

name: CI_prulife_UAT

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  compile_program:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: echo github info
        run: echo ${{ github.sha }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: echo github info
        run: echo ${{ github.sha }}
        
      - name: gen file
        run: echo helo > file

      - name: setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          vesion: latest
        env:
          JF_URL: ${{ secrets.aritfactory_url }}          
          JF_USER: ${{ secrets.aritfactory_USER }}          
          JF_PWD: ${{ secrets.aritfactory_PWD }}

      - name: show JFrong CLI
        run: jf c show
      - name: jfrog upload
        run: |
          jf rt --help
          echo helo
        
